/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mathias.android.owanotify;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int calendar=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int mail=0x7f020002;
        public static final int mail0=0x7f020003;
        public static final int mail1=0x7f020004;
        public static final int mail2=0x7f020005;
        public static final int mail3=0x7f020006;
        public static final int mail4=0x7f020007;
        public static final int mail5=0x7f020008;
        public static final int mail6=0x7f020009;
        public static final int mail7=0x7f02000a;
        public static final int mail8=0x7f02000b;
        public static final int mail9=0x7f02000c;
        public static final int mail9plus=0x7f02000d;
        public static final int mail_num=0x7f02000e;
    }
    public static final class id {
        public static final int alwaysshowmailcount=0x7f050008;
        public static final int calendar=0x7f05000c;
        public static final int checkcalendar=0x7f050007;
        public static final int checkmail=0x7f050006;
        public static final int date=0x7f050002;
        public static final int frequency=0x7f050004;
        public static final int from=0x7f050000;
        public static final int inbox=0x7f05000b;
        public static final int internalviewer=0x7f050005;
        public static final int name=0x7f05000a;
        public static final int password=0x7f05000e;
        public static final int save=0x7f05000f;
        public static final int service=0x7f050003;
        public static final int subject=0x7f050001;
        public static final int url=0x7f050009;
        public static final int username=0x7f05000d;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int main_row=0x7f030001;
        public static final int settings=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
