/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mathias.android.owanotify;

public final class R {
    public static final class array {
        public static final int frequency_names=0x7f050000;
        public static final int frequency_values=0x7f050001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int calendar=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int mail=0x7f020002;
        public static final int mail0=0x7f020003;
        public static final int mail1=0x7f020004;
        public static final int mail2=0x7f020005;
        public static final int mail3=0x7f020006;
        public static final int mail4=0x7f020007;
        public static final int mail5=0x7f020008;
        public static final int mail6=0x7f020009;
        public static final int mail7=0x7f02000a;
        public static final int mail8=0x7f02000b;
        public static final int mail9=0x7f02000c;
        public static final int mail9plus=0x7f02000d;
    }
    public static final class id {
        public static final int date=0x7f070002;
        public static final int from=0x7f070000;
        public static final int subject=0x7f070001;
        public static final int text=0x7f070003;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int main_row=0x7f030001;
        public static final int reademail=0x7f030002;
    }
    public static final class string {
        /**  alwaysshowcount 
         */
        public static final int alwaysshowcount_key=0x7f06001d;
        public static final int alwaysshowcount_summary=0x7f06001f;
        public static final int alwaysshowcount_title=0x7f06001e;
        public static final int app_name=0x7f060000;
        public static final int calendar_defaultvalue=0x7f06002f;
        public static final int calendar_dialogtitle=0x7f06002e;
        /**  calendar 
         */
        public static final int calendar_key=0x7f06002b;
        public static final int calendar_summary=0x7f06002d;
        public static final int calendar_title=0x7f06002c;
        /**  dontcheckcalendar 
         */
        public static final int dontcheckcalendar_key=0x7f060020;
        public static final int dontcheckcalendar_summary=0x7f060022;
        public static final int dontcheckcalendar_title=0x7f060021;
        /**  dontcheckemail 
         */
        public static final int dontcheckemail_key=0x7f06001a;
        public static final int dontcheckemail_summary=0x7f06001c;
        public static final int dontcheckemail_title=0x7f06001b;
        public static final int frequency_dialogtitle=0x7f060004;
        /**  frequency 
         */
        public static final int frequency_key=0x7f060001;
        public static final int frequency_summary=0x7f060003;
        public static final int frequency_title=0x7f060002;
        public static final int inbox_defaultvalue=0x7f06002a;
        public static final int inbox_dialogtitle=0x7f060029;
        /**  inbox 
         */
        public static final int inbox_key=0x7f060026;
        public static final int inbox_summary=0x7f060028;
        public static final int inbox_title=0x7f060027;
        /**  internalviewer 
         */
        public static final int internalviewer_key=0x7f060023;
        public static final int internalviewer_summary=0x7f060025;
        public static final int internalviewer_title=0x7f060024;
        public static final int name_defaultvalue=0x7f060011;
        public static final int name_dialogtitle=0x7f060010;
        /**  name 
         */
        public static final int name_key=0x7f06000d;
        public static final int name_summary=0x7f06000f;
        public static final int name_title=0x7f06000e;
        /**  onlyoverwifi 
         */
        public static final int onlyoverwifi_key=0x7f060005;
        public static final int onlyoverwifi_summary=0x7f060007;
        public static final int onlyoverwifi_title=0x7f060006;
        public static final int password_dialogtitle=0x7f060019;
        /**  password 
         */
        public static final int password_key=0x7f060016;
        public static final int password_summary=0x7f060018;
        public static final int password_title=0x7f060017;
        public static final int url_defaultvalue=0x7f06000c;
        public static final int url_dialogtitle=0x7f06000b;
        /**  url 
         */
        public static final int url_key=0x7f060008;
        public static final int url_summary=0x7f06000a;
        public static final int url_title=0x7f060009;
        public static final int username_dialogtitle=0x7f060015;
        /**  username 
         */
        public static final int username_key=0x7f060012;
        public static final int username_summary=0x7f060014;
        public static final int username_title=0x7f060013;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
