/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mathias.android.acast;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int downloaded=0x7f020000;
        public static final int downloaded_bm=0x7f020001;
        public static final int downloaded_done=0x7f020002;
        public static final int downloaded_done_bm=0x7f020003;
        public static final int eject=0x7f020004;
        public static final int forward=0x7f020005;
        public static final int icon=0x7f020006;
        public static final int notdownloaded=0x7f020007;
        public static final int notdownloaded_bm=0x7f020008;
        public static final int notdownloaded_done=0x7f020009;
        public static final int notdownloaded_done_bm=0x7f02000a;
        public static final int pause=0x7f02000b;
        public static final int play=0x7f02000c;
        public static final int question=0x7f02000d;
        public static final int rewind=0x7f02000e;
        public static final int stop=0x7f02000f;
    }
    public static final class id {
        public static final int add=0x7f050005;
        public static final int bookmark=0x7f050011;
        public static final int category=0x7f05000a;
        public static final int description=0x7f05000b;
        public static final int duration=0x7f050012;
        public static final int feedrowicon=0x7f05000e;
        public static final int feedrowtext=0x7f05000f;
        public static final int feedrowtext2=0x7f050010;
        public static final int forward=0x7f050016;
        public static final int icon=0x7f050000;
        public static final int link=0x7f050007;
        public static final int path=0x7f050019;
        public static final int pause=0x7f05001b;
        public static final int play=0x7f05001a;
        public static final int playpause=0x7f050013;
        public static final int progressbar=0x7f050003;
        public static final int pubdate=0x7f050009;
        public static final int reset=0x7f05001c;
        public static final int resume=0x7f05000c;
        public static final int resumetitle=0x7f05000d;
        public static final int rewind=0x7f050015;
        public static final int seekbar=0x7f050017;
        public static final int stop=0x7f050014;
        public static final int surface=0x7f050018;
        public static final int text=0x7f050001;
        public static final int text2=0x7f050002;
        public static final int title=0x7f050006;
        public static final int uri=0x7f050008;
        public static final int url=0x7f050004;
    }
    public static final class layout {
        public static final int download_list=0x7f030000;
        public static final int download_row=0x7f030001;
        public static final int feed_edit=0x7f030002;
        public static final int feed_info=0x7f030003;
        public static final int feed_list=0x7f030004;
        public static final int feed_row=0x7f030005;
        public static final int feeditem_info=0x7f030006;
        public static final int feeditem_list=0x7f030007;
        public static final int player=0x7f030008;
        public static final int videoplayer=0x7f030009;
    }
    public static final class string {
        public static final int add=0x7f040003;
        /**  feeds_list menu items 
         */
        public static final int addfeed=0x7f040008;
        public static final int app_name=0x7f040001;
        /**  feeditem_info 
         */
        public static final int bookmark=0x7f040007;
        /**  download_list 
         */
        public static final int cancel=0x7f040017;
        public static final int cancelall=0x7f040018;
        public static final int deleteitem=0x7f04000f;
        public static final int downloadall=0x7f04000c;
        public static final int downloaditem=0x7f04000e;
        public static final int editfeed=0x7f040009;
        /**  general 
         */
        public static final int hello=0x7f040000;
        public static final int info=0x7f040011;
        /**  feed_list 
         */
        public static final int nofeeditems=0x7f040006;
        /**  feeds_list 
         */
        public static final int nofeeds=0x7f040004;
        public static final int noresume=0x7f040005;
        public static final int pause=0x7f040013;
        /**  videoplayer 
         */
        public static final int play=0x7f040012;
        /**  player 
 media service 
         */
        public static final int playing=0x7f040016;
        /**  feeditem_list menu items 
         */
        public static final int playitem=0x7f04000d;
        public static final int refresh=0x7f040019;
        public static final int refreshfeed=0x7f040010;
        public static final int refreshfeeds=0x7f04000b;
        public static final int removefeed=0x7f04000a;
        public static final int reset=0x7f040014;
        public static final int stop=0x7f040015;
        /**  feed_edit 
         */
        public static final int url=0x7f040002;
    }
}
