/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mathias.android.acast;

public final class R {
    public static final class array {
        public static final int scheduled_update=0x7f050000;
        public static final int scheduled_update_values=0x7f050001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int additem=0x7f020000;
        public static final int digitalpodcast=0x7f020001;
        public static final int downloaded=0x7f020002;
        public static final int downloaded_bm=0x7f020003;
        public static final int downloaded_done=0x7f020004;
        public static final int downloaded_done_bm=0x7f020005;
        public static final int eject=0x7f020006;
        public static final int findinresults=0x7f020007;
        public static final int forward=0x7f020008;
        public static final int icon=0x7f020009;
        public static final int importopml=0x7f02000a;
        public static final int not_play=0x7f02000b;
        public static final int not_updatecomplete=0x7f02000c;
        public static final int not_updating=0x7f02000d;
        public static final int notdownloaded=0x7f02000e;
        public static final int notdownloaded_bm=0x7f02000f;
        public static final int notdownloaded_done=0x7f020010;
        public static final int notdownloaded_done_bm=0x7f020011;
        public static final int pause=0x7f020012;
        public static final int play=0x7f020013;
        public static final int podcastalleytop50=0x7f020014;
        public static final int podgrove=0x7f020015;
        public static final int question=0x7f020016;
        public static final int rewind=0x7f020017;
        public static final int small_check=0x7f020018;
        public static final int small_downarrow=0x7f020019;
        public static final int small_fire=0x7f02001a;
        public static final int small_play=0x7f02001b;
        public static final int small_sum=0x7f02001c;
        public static final int stop=0x7f02001d;
        public static final int textonly=0x7f02001e;
        public static final int textonly_done=0x7f02001f;
    }
    public static final class id {
        public static final int add=0x7f07001a;
        public static final int addresult=0x7f07001d;
        public static final int author=0x7f070002;
        public static final int bookmark=0x7f07001e;
        public static final int bookmarked=0x7f070014;
        public static final int category=0x7f070009;
        public static final int completed=0x7f070013;
        public static final int description=0x7f07000a;
        public static final int downloaded=0x7f070012;
        public static final int duration=0x7f07002a;
        public static final int feedicon=0x7f070000;
        public static final int feedrowicon=0x7f07000c;
        public static final int feedrowtext=0x7f07000d;
        public static final int feedrowtext2=0x7f07000e;
        public static final int feedrowtext3=0x7f07000f;
        public static final int findinresults=0x7f07001c;
        public static final int forward=0x7f07002d;
        public static final int icon=0x7f070005;
        public static final int importopml=0x7f07001b;
        public static final int latesttitle=0x7f070010;
        public static final int left_text=0x7f07002f;
        public static final int library=0x7f070020;
        public static final int link=0x7f070007;
        public static final int newitems=0x7f070011;
        public static final int next=0x7f070028;
        public static final int player=0x7f070024;
        public static final int playlist=0x7f070021;
        public static final int playpause=0x7f070027;
        public static final int progress=0x7f070026;
        public static final int progressbar=0x7f070006;
        public static final int pubdate=0x7f070003;
        public static final int queue=0x7f070022;
        public static final int resumetitle=0x7f070025;
        public static final int rewind=0x7f07002c;
        public static final int right_text=0x7f070030;
        public static final int screen=0x7f07002e;
        public static final int search=0x7f070023;
        public static final int searchdigitalpodcast=0x7f070018;
        public static final int searchpodgrove=0x7f070017;
        public static final int seekbar=0x7f070029;
        public static final int size=0x7f07001f;
        public static final int statusicon=0x7f070004;
        public static final int stop=0x7f07002b;
        public static final int surface=0x7f070031;
        public static final int text=0x7f070016;
        public static final int title=0x7f070001;
        public static final int top50podcastalley=0x7f070019;
        public static final int total=0x7f070015;
        public static final int updatedate=0x7f07000b;
        public static final int uri=0x7f070008;
    }
    public static final class layout {
        public static final int detailfeeditem_row=0x7f030000;
        public static final int downloaded_list=0x7f030001;
        public static final int downloadqueue_list=0x7f030002;
        public static final int downloadqueue_row=0x7f030003;
        public static final int feed_info=0x7f030004;
        public static final int feed_list=0x7f030005;
        public static final int feed_row=0x7f030006;
        public static final int feedadd=0x7f030007;
        public static final int feedadd_row=0x7f030008;
        public static final int feeditem_info=0x7f030009;
        public static final int feeditem_list=0x7f03000a;
        public static final int feeditem_row=0x7f03000b;
        public static final int menu=0x7f03000c;
        public static final int not_progress=0x7f03000d;
        public static final int play_list=0x7f03000e;
        public static final int player=0x7f03000f;
        public static final int title=0x7f030010;
        public static final int videoplayer=0x7f030011;
    }
    public static final class string {
        /**  AUTODELETECOMPLETED 
         */
        public static final int AUTODELETECOMPLETED_key=0x7f060037;
        public static final int AUTODELETECOMPLETED_summary=0x7f060039;
        public static final int AUTODELETECOMPLETED_title=0x7f060038;
        /**  AUTODELETE 
         */
        public static final int AUTODELETE_key=0x7f06002b;
        public static final int AUTODELETE_summary=0x7f06002d;
        public static final int AUTODELETE_title=0x7f06002c;
        /**  AUTODOWNLOAD 
         */
        public static final int AUTODOWNLOAD_key=0x7f060031;
        public static final int AUTODOWNLOAD_summary=0x7f060033;
        public static final int AUTODOWNLOAD_title=0x7f060032;
        /**  AUTOPLAYNEXT_COMPLETED 
         */
        public static final int AUTOPLAYNEXT_COMPLETED_key=0x7f060043;
        public static final int AUTOPLAYNEXT_COMPLETED_summary=0x7f060045;
        public static final int AUTOPLAYNEXT_COMPLETED_title=0x7f060044;
        /**  AUTOPLAYNEXT_DOWNLOADED 
         */
        public static final int AUTOPLAYNEXT_DOWNLOADED_key=0x7f060040;
        public static final int AUTOPLAYNEXT_DOWNLOADED_summary=0x7f060042;
        public static final int AUTOPLAYNEXT_DOWNLOADED_title=0x7f060041;
        /**  AUTOPLAYNEXT 
         */
        public static final int AUTOPLAYNEXT_key=0x7f06003d;
        public static final int AUTOPLAYNEXT_summary=0x7f06003f;
        public static final int AUTOPLAYNEXT_title=0x7f06003e;
        /**  AUTOPLAYPLAYER 
         */
        public static final int AUTOPLAYPLAYER_key=0x7f060046;
        public static final int AUTOPLAYPLAYER_summary=0x7f060048;
        public static final int AUTOPLAYPLAYER_title=0x7f060047;
        /**  AUTOREFRESH 
         */
        public static final int AUTOREFRESH_key=0x7f06002e;
        public static final int AUTOREFRESH_summary=0x7f060030;
        public static final int AUTOREFRESH_title=0x7f06002f;
        /**  FULLSCREEN 
         */
        public static final int FULLSCREEN_key=0x7f06004c;
        public static final int FULLSCREEN_summary=0x7f06004e;
        public static final int FULLSCREEN_title=0x7f06004d;
        /**  preferences 
 ONLYWIFIDOWNLOAD 
         */
        public static final int ONLYWIFIDOWNLOAD_key=0x7f060022;
        public static final int ONLYWIFIDOWNLOAD_summary=0x7f060024;
        public static final int ONLYWIFIDOWNLOAD_title=0x7f060023;
        /**  ONLYWIFISTREAM 
         */
        public static final int ONLYWIFISTREAM_key=0x7f060025;
        public static final int ONLYWIFISTREAM_summary=0x7f060027;
        public static final int ONLYWIFISTREAM_title=0x7f060026;
        /**  ONLYWIFIUPDATE 
         */
        public static final int ONLYWIFIUPDATE_key=0x7f060028;
        public static final int ONLYWIFIUPDATE_summary=0x7f06002a;
        public static final int ONLYWIFIUPDATE_title=0x7f060029;
        /**  OPENINFORMATION 
         */
        public static final int OPENINFORMATION_key=0x7f06003a;
        public static final int OPENINFORMATION_summary=0x7f06003c;
        public static final int OPENINFORMATION_title=0x7f06003b;
        /**  PLAYERINLANDSCAPE 
         */
        public static final int PLAYERINLANDSCAPE_key=0x7f060049;
        public static final int PLAYERINLANDSCAPE_summary=0x7f06004b;
        public static final int PLAYERINLANDSCAPE_title=0x7f06004a;
        /**  PLAYLISTPLAYER 
         */
        public static final int PLAYLISTPLAYER_key=0x7f06004f;
        public static final int PLAYLISTPLAYER_summary=0x7f060051;
        public static final int PLAYLISTPLAYER_title=0x7f060050;
        /**  RESUMEPARTLYDOWNLOADED 
         */
        public static final int RESUMEPARTLYDOWNLOADED_key=0x7f060034;
        public static final int RESUMEPARTLYDOWNLOADED_summary=0x7f060036;
        public static final int RESUMEPARTLYDOWNLOADED_title=0x7f060035;
        /**  SCHEDULEDUPDATE 
         */
        public static final int SCHEDULEDUPDATE_key=0x7f060052;
        public static final int SCHEDULEDUPDATE_summary=0x7f060054;
        public static final int SCHEDULEDUPDATE_title=0x7f060053;
        public static final int add=0x7f060003;
        /**  feeds_list menu items 
         */
        public static final int addfeed=0x7f06000a;
        /**  general 
         */
        public static final int app_name=0x7f060000;
        /**  feeditem_info 
         */
        public static final int bookmark=0x7f060009;
        /**  download_list 
         */
        public static final int cancel=0x7f06001e;
        public static final int cancelall=0x7f06001f;
        public static final int deleteitem=0x7f060016;
        public static final int downloadall=0x7f06000f;
        public static final int downloaditem=0x7f060015;
        public static final int downloadlast=0x7f060012;
        public static final int downloadlist=0x7f060011;
        public static final int downloadqueue=0x7f060010;
        public static final int editfeed=0x7f06000b;
        public static final int exportlocalopml=0x7f060021;
        public static final int gotolink=0x7f060001;
        /**  feed_add 
         */
        public static final int importlocalopml=0x7f060020;
        public static final int info=0x7f060018;
        /**  feed_list 
         */
        public static final int nofeeditems=0x7f060008;
        /**  feeds_list 
         */
        public static final int nofeeds=0x7f060005;
        public static final int noresults=0x7f060004;
        public static final int noresume=0x7f060006;
        public static final int pause=0x7f06001a;
        /**  videoplayer 
         */
        public static final int play=0x7f060019;
        /**  player 
 media service 
         */
        public static final int playing=0x7f06001d;
        /**  feeditem_list menu items 
         */
        public static final int playitem=0x7f060013;
        public static final int queueitem=0x7f060014;
        public static final int refresh=0x7f060017;
        public static final int refreshall=0x7f06000e;
        public static final int remove=0x7f06000c;
        public static final int removefeed=0x7f06000d;
        public static final int reset=0x7f06001b;
        public static final int settings=0x7f060007;
        public static final int stop=0x7f06001c;
        /**  feed_edit 
         */
        public static final int url=0x7f060002;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
