/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mathias.android.acast;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int confirm=0x7f050002;
        public static final int text1=0x7f050003;
        public static final int title=0x7f050000;
        public static final int url=0x7f050001;
    }
    public static final class layout {
        public static final int feed_edit=0x7f030000;
        public static final int feed_list=0x7f030001;
        public static final int feed_row=0x7f030002;
        public static final int feeds_list=0x7f030003;
    }
    public static final class string {
        public static final int addfeed=0x7f040005;
        public static final int app_name=0x7f040001;
        public static final int confirm=0x7f040004;
        public static final int deleteitem=0x7f04000b;
        public static final int downloaditem=0x7f04000a;
        public static final int editfeed=0x7f040006;
        public static final int hello=0x7f040000;
        public static final int playitem=0x7f040009;
        public static final int refreshfeed=0x7f04000c;
        public static final int refreshfeeds=0x7f040008;
        public static final int removefeed=0x7f040007;
        public static final int title=0x7f040002;
        public static final int url=0x7f040003;
    }
}
